/**
 * Drift guard for the autogenerated README sections (workplan T-R3). Regenerates
 * the tool catalog and the env catalog from the live sources (`allTools`,
 * `.env.example`) and asserts the bytes currently between the AUTOGEN markers in
 * `README.md` match exactly. On mismatch the maintainer must run
 * `npm run gen:readme` to re-sync — the assertion message says so.
 *
 * The test process runs from the repo root (`npm test` -> `node --test` with
 * cwd = repo root), so `README.md` and `.env.example` resolve from `process.cwd()`.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { allTools } from '../src/tools/index.js';
import { PACKAGE_PROFILES, READONLY_PROFILES } from '../src/mcp/registry.js';
import type { ToolSpec } from '../src/mcp/define.js';
import { renderToolTable, renderEnvCatalog } from './helpers/doc-generators.js';

/** The exact text between a `BEGIN`/`END` AUTOGEN marker pair, without the
 * single newline that follows BEGIN and the one that precedes END. */
function sectionBetweenMarkers(readme: string, id: string): string {
  const begin = `<!-- BEGIN AUTOGEN:${id} -->`;
  const end = `<!-- END AUTOGEN:${id} -->`;
  const start = readme.indexOf(begin);
  const stop = readme.indexOf(end);
  assert.notEqual(start, -1, `README is missing the marker ${begin}`);
  assert.notEqual(stop, -1, `README is missing the marker ${end}`);
  assert.ok(start < stop, `README markers for "${id}" are out of order`);
  return readme
    .slice(start + begin.length, stop)
    .replace(/^\n/, '')
    .replace(/\n$/, '');
}

test('README tool catalog is in sync with allTools', () => {
  const readme = readFileSync('README.md', 'utf8');
  const expected = renderToolTable(allTools);
  const actual = sectionBetweenMarkers(readme, 'tools');
  assert.strictEqual(
    actual,
    expected,
    'README Tools table is out of date — run `npm run gen:readme` to regenerate it.',
  );
});

test('README env catalog is in sync with .env.example', () => {
  const readme = readFileSync('README.md', 'utf8');
  const envExample = readFileSync('.env.example', 'utf8');
  const expected = renderEnvCatalog(envExample);
  const actual = sectionBetweenMarkers(readme, 'env');
  assert.strictEqual(
    actual,
    expected,
    'README Configuration table is out of date — run `npm run gen:readme` to regenerate it.',
  );
});

// --- Generator edge cases the live catalog cannot reach ----------------------
//
// The two tests above compare the generators against the real registry, which
// is well-behaved by construction: every description is a sentence and every
// tool name is unique. That leaves the generators' fallback arms unexercised —
// and those arms only ever run on the day someone adds a tool that breaks one
// of those unstated assumptions, which is precisely when a silent misrender
// (a truncated row, a nondeterministic ordering) would slip into the README.

/** A ToolSpec with only the fields the renderers read. */
function specFor(
  name: string,
  pkg: string,
  description: string,
  paths?: ToolSpec['paths'],
): ToolSpec {
  return {
    name,
    title: name,
    description,
    package: pkg,
    annotations: { readOnlyHint: true },
    input: {},
    handler: () => ({ content: [] }),
    ...(paths === undefined ? {} : { paths }),
  };
}

test('an empty paths list renders as unrestricted, not as a blank cell', () => {
  // `paths` absent and `paths: []` mean the same thing — no auth-path
  // restriction — and every tool in the live registry expresses it the first
  // way, so only the second arm can rot. A blank cell would read as "this tool
  // works on no auth path at all", which is the opposite of what it means.
  const table = renderToolTable([specFor('instagram_x', 'core', 'Unrestricted.', [])]);
  assert.match(table, /\| `instagram_x` \| core \| both \|/);

  const restricted = renderToolTable([
    specFor('instagram_y', 'core', 'Path B only.', ['fb-login']),
  ]);
  assert.match(restricted, /\| `instagram_y` \| core \| fb-login \|/);
});

test('a description with no sentence terminator is rendered whole, not dropped', () => {
  // `firstSentence` looks for `.`/`!`/`?` followed by whitespace or end of
  // input. A description without one — a fragment, or a trailing token like
  // `business_discovery.username` — must fall back to the full trimmed text.
  // Returning `''` here would render an empty Summary cell that still passes a
  // byte-comparison drift test, because the README would be regenerated with
  // the same emptiness.
  const table = renderToolTable([specFor('instagram_x', 'core', '  a fragment with no stop  ')]);
  assert.match(table, /\| a fragment with no stop \|/);

  // And the normal case still stops at the first sentence, with the period kept.
  const stopped = renderToolTable([specFor('instagram_y', 'core', 'First. Second.')]);
  assert.match(stopped, /\| First\. \|/);
});

test('two tools sharing a name and package keep a stable relative order', () => {
  // The name comparison is the last tie-break in the sort. If its equal arm
  // returned anything but 0 the comparator would stop being a total order, and
  // `Array.prototype.sort` is only stable for a consistent comparator — the
  // README rows could then reorder between runs and fail the drift test with no
  // source change. A duplicate name is a registry bug, but it must not turn
  // into a *nondeterministic* one.
  const a = specFor('instagram_dup', 'core', 'First copy.');
  const b = specFor('instagram_dup', 'core', 'Second copy.');
  const forward = renderToolTable([a, b]);
  assert.equal(forward, renderToolTable([a, b]), 'the same input must render the same bytes');
  assert.ok(
    forward.indexOf('First copy.') < forward.indexOf('Second copy.'),
    'equal keys must preserve input order',
  );
});

/**
 * How many tools a profile actually registers: its packages intersected with the
 * surface, and — for a profile that is read-only by definition — only the tools
 * carrying `readOnlyHint`. This is the same resolution the registry performs, so
 * the README table cannot claim a number the server does not produce.
 */
function toolsInProfile(profile: string): number {
  const packages = new Set(PACKAGE_PROFILES[profile] ?? []);
  const selected = allTools.filter((spec) => packages.has(spec.package));
  return READONLY_PROFILES.includes(profile)
    ? selected.filter((spec) => spec.annotations.readOnlyHint === true).length
    : selected.length;
}

/**
 * The hand-written profile table is the only place the README states what an
 * operator gets for each `IG_TOOL_PACKAGES` value. `registry.test.ts` pins 15 and
 * 21 as literals annotated "(README table)", but nothing ever read the README to
 * check — so adding a tool moved the code and left the table behind, silently.
 */
test('README profile table states the tool count each profile really registers', () => {
  const readme = readFileSync('README.md', 'utf8');
  // Column 2 is captured, not skipped over: it is the literal an operator pastes into
  // IG_TOOL_PACKAGES, and it is checked below.
  const rows = [...readme.matchAll(/^\| `([a-z]+)`[^|]*\| ([^|]*)\|[^|]*\| (\d+) \|$/gm)];
  const stated = new Map(rows.map(([, profile, , count]) => [profile, Number(count)]));
  // Not `size > 0`: a floor lets a row go quiet. A row naming a profile the registry
  // does not define is not a documentation slip either — selectPackages falls through
  // to its explicit-list branch and throws at startup, so the operator who followed the
  // table cannot start the server at all.
  assert.deepEqual(
    [...stated.keys()].sort(),
    [...Object.keys(PACKAGE_PROFILES), 'all'].sort(),
    'the README profile table and PACKAGE_PROFILES name different profiles.',
  );

  for (const profile of Object.keys(PACKAGE_PROFILES)) {
    assert.strictEqual(
      stated.get(profile),
      toolsInProfile(profile),
      `README claims a different tool count for the \`${profile}\` profile than the ` +
        `registry resolves. An operator picks a profile by this number.`,
    );
  }
  assert.strictEqual(
    stated.get('all'),
    allTools.length,
    'README claims a different size for the `all` profile than the full surface.',
  );

  // The count is what an operator compares; the package list is what they copy. A wrong
  // list is the quieter failure of the two: it is still a valid explicit selection, so
  // the server starts and simply exposes a different surface than the row promised.
  // `all` spells its value in prose, so which rows carry a literal list is asserted
  // rather than assumed — a list that decayed into prose would otherwise be checked by
  // nothing at all.
  const spelled = new Map<string, string>();
  for (const [, profile, packages] of rows) {
    const literal = /^`([a-z, ]+)`$/.exec((packages ?? '').trim());
    if (profile !== undefined && literal?.[1] !== undefined) spelled.set(profile, literal[1]);
  }
  assert.deepEqual(
    [...spelled.keys()].sort(),
    Object.keys(PACKAGE_PROFILES).sort(),
    'the README rows spelling an explicit package list are no longer exactly the profiles ' +
      'PACKAGE_PROFILES expands.',
  );
  for (const [profile, packages] of spelled) {
    assert.deepEqual(
      packages.split(',').map((pkg) => pkg.trim()),
      [...(PACKAGE_PROFILES[profile] ?? [])],
      `README spells the \`${profile}\` profile as a different package list than the registry ` +
        'expands it to. An operator who copies that value gets a different tool surface.',
    );
  }
});

test('README tools badge counts the tools the server exposes', () => {
  const readme = readFileSync('README.md', 'utf8');
  const badge = /badge\/tools-(\d+)-/.exec(readme);
  assert.notEqual(badge, null, 'README no longer carries a tools badge');
  assert.strictEqual(
    Number(badge?.[1]),
    allTools.length,
    'the README tools badge is stale — it is the first number anyone reads.',
  );
});
