/**
 * Drift guard for the autogenerated README sections (workplan T-R3). Regenerates
 * the tool catalog and the env catalog from the live sources (`allTools`,
 * `.env.example`) and asserts the bytes currently between the AUTOGEN markers in
 * `README.md` match exactly. On mismatch the maintainer must run
 * `npm run gen:readme` to re-sync — the assertion message says so.
 *
 * The test process runs from the repo root (`npm test` -> `node --test` with
 * cwd = repo root), so `README.md` and `.env.example` resolve from `process.cwd()`.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { allTools } from '../src/tools/index.js';
import { renderToolTable, renderEnvCatalog } from './helpers/doc-generators.js';

/** The exact text between a `BEGIN`/`END` AUTOGEN marker pair, without the
 * single newline that follows BEGIN and the one that precedes END. */
function sectionBetweenMarkers(readme: string, id: string): string {
  const begin = `<!-- BEGIN AUTOGEN:${id} -->`;
  const end = `<!-- END AUTOGEN:${id} -->`;
  const start = readme.indexOf(begin);
  const stop = readme.indexOf(end);
  assert.notEqual(start, -1, `README is missing the marker ${begin}`);
  assert.notEqual(stop, -1, `README is missing the marker ${end}`);
  assert.ok(start < stop, `README markers for "${id}" are out of order`);
  return readme
    .slice(start + begin.length, stop)
    .replace(/^\n/, '')
    .replace(/\n$/, '');
}

test('README tool catalog is in sync with allTools', () => {
  const readme = readFileSync('README.md', 'utf8');
  const expected = renderToolTable(allTools);
  const actual = sectionBetweenMarkers(readme, 'tools');
  assert.strictEqual(
    actual,
    expected,
    'README Tools table is out of date — run `npm run gen:readme` to regenerate it.',
  );
});

test('README env catalog is in sync with .env.example', () => {
  const readme = readFileSync('README.md', 'utf8');
  const envExample = readFileSync('.env.example', 'utf8');
  const expected = renderEnvCatalog(envExample);
  const actual = sectionBetweenMarkers(readme, 'env');
  assert.strictEqual(
    actual,
    expected,
    'README Configuration table is out of date — run `npm run gen:readme` to regenerate it.',
  );
});
