/**
 * Release gate: three-channel version-drift test (workplan T-R7).
 *
 * `package.json` is the single source of truth for the version. The MCP-registry
 * manifest (`server.json`, produced by T-R5) and the MCPB bundle manifest
 * (`manifest.json`, produced by T-R6) each carry their own copy of the version
 * that must never drift from it. This test reads all three from the repo root and
 * asserts they agree on both version and package/server identity.
 *
 * The test process runs from the repo root (`npm test` -> `node --test` with
 * cwd = repo root), so the files resolve from `process.cwd()`. If cwd does not
 * hold a `package.json` (e.g. the compiled test is invoked directly from
 * elsewhere), the repo root is instead found by walking up from this file's own
 * location.
 *
 * NOTE: `server.json` and `manifest.json` are generated by sibling release tasks
 * in the same wave and may be absent when this test runs in isolation, in which
 * case the reads below fail with a message naming the missing file. Once the
 * release lane is integrated the files exist and the assertions run for real.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The npm package name (`package.json.name`). */
const PACKAGE_NAME = 'instagram-mcp-ai';
/** The MCP-registry server name (`server.json.name`, reverse-DNS). */
const REGISTRY_NAME = 'io.github.IvanBBaev/instagram-mcp-ai';

/** True for a plain JSON object (not `null`, not an array). */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Locate the repo root: the nearest directory containing a `package.json`. Prefer
 * `process.cwd()` (the test runner's working directory); otherwise walk up from
 * this compiled test's own directory to the filesystem root.
 */
function findRepoRoot(): string {
  const candidates: string[] = [process.cwd()];
  let dir = dirname(fileURLToPath(import.meta.url));
  let parent = dirname(dir);
  while (dir !== parent) {
    candidates.push(dir);
    dir = parent;
    parent = dirname(dir);
  }
  candidates.push(dir); // filesystem root

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'package.json'))) return candidate;
  }
  throw new Error(
    `could not locate repo root: no package.json found in any of ${candidates.join(', ')}`,
  );
}

const repoRoot = findRepoRoot();

/** Read + parse a JSON file from the repo root; fail clearly if it is absent. */
function readRepoJson(file: string): Record<string, unknown> {
  const path = join(repoRoot, file);
  if (!existsSync(path)) {
    throw new Error(
      `${file} not found at ${path} — it is generated by a sibling release task ` +
        `(server.json by T-R5, manifest.json by T-R6) and MUST exist once the ` +
        `release lane is integrated.`,
    );
  }
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'));
  if (!isRecord(parsed)) {
    throw new Error(`${file} did not parse to a JSON object`);
  }
  return parsed;
}

test('package.json is the single source of truth for name and version', () => {
  const pkg = readRepoJson('package.json');
  assert.equal(pkg.name, PACKAGE_NAME, 'package.json.name must be the npm package name');
  assert.equal(typeof pkg.version, 'string', 'package.json.version must be a string');
  assert.ok((pkg.version as string).length > 0, 'package.json.version must be non-empty');
});

test('server.json carries the registry name and matches the source-of-truth version', () => {
  const pkg = readRepoJson('package.json');
  const server = readRepoJson('server.json');

  assert.equal(server.name, REGISTRY_NAME, 'server.json.name must be the MCP-registry name');
  assert.equal(server.version, pkg.version, 'server.json.version must equal package.json.version');

  // The registry schema repeats the version inside packages[]; keep it in lockstep.
  const packages = server.packages;
  if (Array.isArray(packages)) {
    for (const entry of packages) {
      if (isRecord(entry) && 'version' in entry) {
        assert.equal(
          entry.version,
          pkg.version,
          'server.json packages[].version must equal package.json.version',
        );
      }
    }
  }
});

test('manifest.json (MCPB) matches the source-of-truth version and a consistent name', () => {
  const pkg = readRepoJson('package.json');
  const manifest = readRepoJson('manifest.json');

  assert.equal(
    manifest.version,
    pkg.version,
    'manifest.json.version must equal package.json.version',
  );

  // The MCPB manifest name must be consistent with the package identity — either
  // the npm package name or the reverse-DNS registry name, never anything else.
  assert.ok(
    manifest.name === PACKAGE_NAME || manifest.name === REGISTRY_NAME,
    `manifest.json.name (${String(manifest.name)}) must be "${PACKAGE_NAME}" or "${REGISTRY_NAME}"`,
  );
});

test('all three channels agree on a single version (single source of truth)', () => {
  const pkgVersion = readRepoJson('package.json').version;
  const serverVersion = readRepoJson('server.json').version;
  const manifestVersion = readRepoJson('manifest.json').version;

  assert.equal(serverVersion, pkgVersion, 'server.json version must equal package.json version');
  assert.equal(
    manifestVersion,
    pkgVersion,
    'manifest.json version must equal package.json version',
  );
});
