/**
 * Regenerate the autogenerated README sections from the live sources.
 *
 * Run via `npm run gen:readme`, which builds first so the COMPILED generators
 * and tool registry exist under `dist/`. This script imports those built
 * artifacts, reads `README.md` + `.env.example`, replaces the text between each
 * `AUTOGEN` marker pair, and writes `README.md` back. Dependency-free (only
 * `node:` builtins). It is a plain ESM script, deliberately outside `tsconfig`
 * (`scripts/**` is not compiled).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { allTools } from '../dist/src/tools/index.js';
import { renderToolTable, renderEnvCatalog } from '../dist/test/helpers/doc-generators.js';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const readmePath = join(repoRoot, 'README.md');
const envExamplePath = join(repoRoot, '.env.example');

/** Replace the text between a `BEGIN`/`END` AUTOGEN marker pair with `body`. */
function replaceSection(source, id, body) {
  const begin = `<!-- BEGIN AUTOGEN:${id} -->`;
  const end = `<!-- END AUTOGEN:${id} -->`;
  const start = source.indexOf(begin);
  const stop = source.indexOf(end);
  if (start === -1 || stop === -1 || start > stop) {
    throw new Error(`README.md is missing or has malformed AUTOGEN markers for "${id}".`);
  }
  return source.slice(0, start + begin.length) + '\n' + body + '\n' + source.slice(stop);
}

let readme = readFileSync(readmePath, 'utf8');
readme = replaceSection(readme, 'tools', renderToolTable(allTools));
readme = replaceSection(readme, 'env', renderEnvCatalog(readFileSync(envExamplePath, 'utf8')));
writeFileSync(readmePath, readme);

console.log('README.md AUTOGEN sections regenerated.');
